In [1]:
import numpy as np

In [2]:
scalar = 5.0
print("Scalar: ", scalar, " | Shape: ", np.array(scalar).shape)

Scalar:  5.0  | Shape:  ()


In [3]:
vector = np.array([2,7,4])
print("Vector: ", vector, "| Shape: ", vector.shape)

Vector:  [2 7 4] | Shape:  (3,)


In [8]:
matrix = np.array([[1,3], [5,2],[8,6]])
print("Matrix:\n", matrix, "\n Shape:", matrix.shape)

Matrix:
 [[1 3]
 [5 2]
 [8 6]] 
 Shape: (3, 2)


In [9]:
tensor = np.zeros((32,244,224,3))
print("Tensor shape: ", tensor.shape)

Tensor shape:  (32, 244, 224, 3)


## Task 1:- Create a numpy vector of shape (5,) with values [10, 20, 30, 40, 50]. Print its shape and data type.

In [11]:
vector = np.array([10,20,30,40,50])
print("vector:,",vector,"| Shape:",vector.shape)

vector:, [10 20 30 40 50] | Shape: (5,)


## task 2:- Create a (2, 3) matrix representing 2 students and 3 exam scores. What would a tensor look like for 10 students?

In [15]:
matrix =np.array([[56,78,90], [80,78,83]])
print("matrix:",matrix,"| shape:",matrix.shape)

matrix: [[56 78 90]
 [80 78 83]] | shape: (2, 3)


In [16]:
import numpy as np

tensor = np.array([
    [   # Class 1
        [85, 90, 78],
        [72, 88, 91],
        [80, 75, 85],
        [60, 70, 65],
        [95, 92, 88],
        [78, 81, 79],
        [84, 86, 90],
        [73, 77, 80],
        [88, 89, 85],
        [91, 93, 94]
    ],
    [   # Class 2
        [75, 80, 70],
        [68, 74, 72],
        [82, 85, 88],
        [90, 91, 89],
        [77, 79, 81],
        [85, 87, 90],
        [69, 72, 75],
        [95, 96, 94],
        [83, 84, 82],
        [78, 80, 76]
    ]
])

print("Tensor shape:", tensor.shape)
print("\nTensor data:\n", tensor)

Tensor shape: (2, 10, 3)

Tensor data:
 [[[85 90 78]
  [72 88 91]
  [80 75 85]
  [60 70 65]
  [95 92 88]
  [78 81 79]
  [84 86 90]
  [73 77 80]
  [88 89 85]
  [91 93 94]]

 [[75 80 70]
  [68 74 72]
  [82 85 88]
  [90 91 89]
  [77 79 81]
  [85 87 90]
  [69 72 75]
  [95 96 94]
  [83 84 82]
  [78 80 76]]]
